# Generated by Django 5.2.4 on 2025-07-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_all_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='solution_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
