# Generated by Django 5.2.4 on 2025-07-20 18:33

from django.db import migrations

def populate_data(apps, schema_editor):
    """
    Poblamos las tablas t_client_type y t_support_channel con datos iniciales.
    """
    # Obtenemos los modelos históricos para esta migración
    ClientType = apps.get_model('core', 'ClientType')
    SupportChannel = apps.get_model('core', 'SupportChannel')

    # --- Datos para t_client_type ---
    client_types_to_add = [
        'Installer',
        'Distributor',
        'Property Manager',
        'End Customer',
    ]
    for type_name in client_types_to_add:
        ClientType.objects.get_or_create(name=type_name)

    # --- Datos para t_support_channel ---
    support_channels_to_add = [
        {'name': 'Call by WhatsApp', 'is_call': True},
        {'name': 'Call by Kerberus', 'is_call': True},
        {'name': 'Message by WhatsApp', 'is_call': False},
        {'name': 'Email', 'is_call': False},
        {'name': 'WeChat', 'is_call': False},
        {'name': 'Message by FreshDesk', 'is_call': False},
    ]
    for channel_data in support_channels_to_add:
        SupportChannel.objects.get_or_create(name=channel_data['name'], defaults={'is_call': channel_data['is_call']})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_support'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
