# Generated by Django 5.2.4 on 2025-07-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_support_solution_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='support_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supportchannel'),
        ),
    ]
