# Generated by Django 5.2.4 on 2025-07-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_support_support_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditbalance',
            options={'permissions': [('can_recharge_credit', 'Can recharge credit balance')]},
        ),
    ]
