# Generated by Django 5.2.4 on 2025-07-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_american_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='call_status',
            field=models.CharField(blank=True, choices=[('RECEIVED', 'Received'), ('MISSED', 'Missed')], max_length=50, null=True),
        ),
    ]
