# Generated by Django 5.2.4 on 2025-07-31 20:36

from django.db import migrations
from django.db import migrations

def rename_channel(apps, schema_editor):
    """
    Busca el canal 'Training Presential' y lo renombra a 'Presential Training'.
    """
    SupportChannel = apps.get_model('core', 'SupportChannel')
    
    try:
        # Busca el registro con el nombre antiguo
        channel_to_update = SupportChannel.objects.get(name="Training Presential")
        
        # Le asigna el nuevo nombre y lo guarda
        channel_to_update.name = "Presential Training"
        channel_to_update.save()
        
        print("\n -> Se ha renombrado 'Training Presential' a 'Presential Training' exitosamente.")
        
    except SupportChannel.DoesNotExist:
        # Esto se ejecuta si el registro ya fue renombrado o no existe
        print("\n ! No se encontró el canal 'Training Presential'. No se realizó ningún cambio.")


class Migration(migrations.Migration):

    dependencies = [
        # Reemplaza '00XX_...' con el nombre de tu migración anterior
        ('core', '0006_create_user_groups'),
    ]

    operations = [
        migrations.RunPython(rename_channel),
    ]
