# Generated by Django 5.2.4 on 2025-08-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_training_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
