# Generated by Django 5.2.4 on 2025-07-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_country_phone_code'),
        ('core', '0008_populate_phone_codes'),
    ]

    operations = [
    ]
