# Generated by Django 5.2.4 on 2025-07-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250720_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
