# Generated by Django 5.2.4 on 2025-07-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_populate_new_statuses_and_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_minutes', models.IntegerField(default=3000)),
            ],
        ),
    ]
